name: Deploy Blazor WASM to Vercel

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Blazor App
        run: dotnet publish -c Release -o publish_output

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy publish_output/wwwroot --local-config=vercel.json --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
